const sakuraSkin = {
  name: '桜',
  colors: {
    background: '#fff4f8',
    surface: '#ffffff',
    primary: '#e91e63',
    accent: '#c2185b',
    text: '#3c2a2a',
    border: '#f8bbd0',
    shadow: 'rgba(0,0,0,0.1)',
    card: '#ffffff',
    tagShrine: '#fdeff2',
    tagDiety: '#fce4ec',
    tagUser: '#f9e1eb',
    tagShrineText: '#ad1457',
    tagDietyText: '#880e4f',
    tagUserText: '#6a1b9a',
    rankingTabBg: '#ffffff',
    rankingTabActiveBg: '#fff4f8',
    rankingRowBg: '#ffffff',
    rankingRowBorder: '#f8bbd0',
    rankingSection: '#374151',
    logText: '#3c2a2a',
    section: '#374151',
    rankingBadge1: '#ffd700',
    rankingBadge2: '#c0c0c0',
    rankingBadge3: '#cd7f32',
    rankingBadgeOther: '#f8bbd0',
    rankingBadgeText: '#3c2a2a',
    scrollbarThumb: '#f8bbd0',
    scrollbarTrack: '#fdeff2',
    scrollbarThumbHover: '#e91e63',
    tabInactive: 'linear-gradient(to bottom, #eac1d5 0%, #fdeff2 100%)',
  },
  borderRadius: '1.5rem',
  fontFamily: '"Noto Serif JP", serif',
  boxShadow: '0 8px 32px 0 rgba(0, 0, 0, 0.1), 0 0 0 6px #fff4f8',
  modal: {
    maxWidth: '600px',
    padding: '2rem 1.5rem',
    background: 'linear-gradient(135deg, #ffffff 0%, #fff4f8 100%)',
  },
};

export default sakuraSkin;
